stages:
  - deploy

deploy:
    stage: deploy
    only:
      refs:
        - gitlab-ci
        - main
      changes:
        - DataIngestor/*
        - DataProcessor/*
        - ShowData/*
    before_script:
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    script:
      - ssh $SSH_USER@$SSH_HOST -i ~/.ssh/id_rsa "sudo git -C $PROJECT_PATH pull && sudo chown -R $SSH_USER:$SSH_USER $PROJECT_PATH"
      - |
        echo "all:
                children:
                  dataserver:
                    hosts: localhost
                    vars:
                      ansible_user: ubuntu" > inventory
      - scp -r -i ~/.ssh/id_rsa inventory $SSH_USER@$SSH_HOST:$PROJECT_PATH/deployment
      - ssh $SSH_USER@$SSH_HOST ~/.ssh/id_rsa "cd $PROJECT_PATH/deployment && ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory ansible/run_project.yaml"

