version: "3"
services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  showdata:
    image: showdata
    build: .
    expose:
      - "5000"
    environment:
      S3_BUCKET_NAME: tatum-data
      S3_ACCESS_KEY: ACCESS_KEY
      S3_SECRET_KEY: SECRET_KEY
      S3_REGION: us-east-1
      GCS_UPLOAD_BUCKET: tatum-data
      GOOGLE_API_FILE: "/etc/key.json"
      STORAGE_PROVIDER: s3
      PORT: 5000
    volumes:
      - ./key.json:/etc/key.json
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showdata.rule=PathPrefix(`/`)"
      - "traefik.http.routers.showdata.entrypoints=web"

