version: "3"
services:
  data-processor:
    image: data-processor
    build: .
    environment:
      S3_BUCKET_NAME: tatum-data
      S3_ACCESS_KEY: ACCESS_KEY
      S3_SECRET_KEY: SECRET_KEY
      S3_REGION: us-east-1
      S3_DOWNLOAD_BUCKET: "tatum-data-download"
      S3_UPLOAD_BUCKET: "tatum-data"
      GCS_DOWNLOAD_BUCKET: "tatum-data-download"
      GCS_UPLOAD_BUCKET: "tatum-data"
      GOOGLE_API_FILE: "/etc/key.json"
      DOWNLOAD_PATH: /tmp/download
      PROCESSED_FOLDER: /tmp/processed
      STORAGE_PROVIDER: gcp,s3
    volumes:
      - ./key.json:/etc/key.json
